package com.sethchhim.kuboo_client.synthetic

import android.app.Activity
import com.sethchhim.kuboo_client.R
import android.view.View
import android.widget.Button
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.ProgressBar
import android.widget.TextView

/**
 * Replacements for the Kotlin Android Extensions synthetic view accessors, which were
 * removed from Kotlin. Each property keeps the generated name the call sites already use,
 * so the views are still reached by id — now through findViewById.
 *
 * Generated from the ids referenced in code and their types in res/layout.
 */

val View.about_item_faq_textView1: TextView get() = findViewById(R.id.about_item_faq_textView1)
val Activity.about_item_faq_textView1: TextView get() = findViewById(R.id.about_item_faq_textView1)
val View.about_item_faq_textView2: TextView get() = findViewById(R.id.about_item_faq_textView2)
val Activity.about_item_faq_textView2: TextView get() = findViewById(R.id.about_item_faq_textView2)
val View.browser_item_content_folder_imageView1: ImageView get() = findViewById(R.id.browser_item_content_folder_imageView1)
val Activity.browser_item_content_folder_imageView1: ImageView get() = findViewById(R.id.browser_item_content_folder_imageView1)
val View.browser_item_content_folder_imageView2: ImageView get() = findViewById(R.id.browser_item_content_folder_imageView2)
val Activity.browser_item_content_folder_imageView2: ImageView get() = findViewById(R.id.browser_item_content_folder_imageView2)
val View.browser_item_content_folder_imageView3: ImageView get() = findViewById(R.id.browser_item_content_folder_imageView3)
val Activity.browser_item_content_folder_imageView3: ImageView get() = findViewById(R.id.browser_item_content_folder_imageView3)
val View.browser_item_content_folder_imageView4: ImageView get() = findViewById(R.id.browser_item_content_folder_imageView4)
val Activity.browser_item_content_folder_imageView4: ImageView get() = findViewById(R.id.browser_item_content_folder_imageView4)
val View.browser_item_content_folder_materialBadgeTextView: com.matrixxun.starry.badgetextview.MaterialBadgeTextView get() = findViewById(R.id.browser_item_content_folder_materialBadgeTextView)
val Activity.browser_item_content_folder_materialBadgeTextView: com.matrixxun.starry.badgetextview.MaterialBadgeTextView get() = findViewById(R.id.browser_item_content_folder_materialBadgeTextView)
val View.browser_item_content_folder_sparkButton: com.varunest.sparkbutton.SparkButton? get() = findViewById(R.id.browser_item_content_folder_sparkButton)
val Activity.browser_item_content_folder_sparkButton: com.varunest.sparkbutton.SparkButton? get() = findViewById(R.id.browser_item_content_folder_sparkButton)
val View.browser_item_content_folder_textView1: TextView get() = findViewById(R.id.browser_item_content_folder_textView1)
val Activity.browser_item_content_folder_textView1: TextView get() = findViewById(R.id.browser_item_content_folder_textView1)
val View.browser_item_content_folder_textView2: TextView get() = findViewById(R.id.browser_item_content_folder_textView2)
val Activity.browser_item_content_folder_textView2: TextView get() = findViewById(R.id.browser_item_content_folder_textView2)
val View.browser_item_content_media_force_list_constraintLayout: androidx.constraintlayout.widget.ConstraintLayout? get() = findViewById(R.id.browser_item_content_media_force_list_constraintLayout)
val Activity.browser_item_content_media_force_list_constraintLayout: androidx.constraintlayout.widget.ConstraintLayout? get() = findViewById(R.id.browser_item_content_media_force_list_constraintLayout)
val View.browser_item_content_media_force_list_imageView1: ImageView get() = findViewById(R.id.browser_item_content_media_force_list_imageView1)
val Activity.browser_item_content_media_force_list_imageView1: ImageView get() = findViewById(R.id.browser_item_content_media_force_list_imageView1)
val View.browser_item_content_media_force_list_imageView2: ImageView get() = findViewById(R.id.browser_item_content_media_force_list_imageView2)
val Activity.browser_item_content_media_force_list_imageView2: ImageView get() = findViewById(R.id.browser_item_content_media_force_list_imageView2)
val View.browser_item_content_media_force_list_imageView3: ImageView? get() = findViewById(R.id.browser_item_content_media_force_list_imageView3)
val Activity.browser_item_content_media_force_list_imageView3: ImageView? get() = findViewById(R.id.browser_item_content_media_force_list_imageView3)
val View.browser_item_content_media_force_list_textView1: TextView get() = findViewById(R.id.browser_item_content_media_force_list_textView1)
val Activity.browser_item_content_media_force_list_textView1: TextView get() = findViewById(R.id.browser_item_content_media_force_list_textView1)
val View.browser_item_content_media_force_list_textView2: TextView get() = findViewById(R.id.browser_item_content_media_force_list_textView2)
val Activity.browser_item_content_media_force_list_textView2: TextView get() = findViewById(R.id.browser_item_content_media_force_list_textView2)
val View.browser_item_content_media_imageView: ImageView? get() = findViewById(R.id.browser_item_content_media_imageView)
val Activity.browser_item_content_media_imageView: ImageView? get() = findViewById(R.id.browser_item_content_media_imageView)
val View.browser_item_download_imageView1: ImageView get() = findViewById(R.id.browser_item_download_imageView1)
val Activity.browser_item_download_imageView1: ImageView get() = findViewById(R.id.browser_item_download_imageView1)
val View.browser_item_download_imageView2: ImageView get() = findViewById(R.id.browser_item_download_imageView2)
val Activity.browser_item_download_imageView2: ImageView get() = findViewById(R.id.browser_item_download_imageView2)
val View.browser_item_download_imageView3: ImageView get() = findViewById(R.id.browser_item_download_imageView3)
val Activity.browser_item_download_imageView3: ImageView get() = findViewById(R.id.browser_item_download_imageView3)
val View.browser_item_download_imageView4: ImageView get() = findViewById(R.id.browser_item_download_imageView4)
val Activity.browser_item_download_imageView4: ImageView get() = findViewById(R.id.browser_item_download_imageView4)
val View.browser_item_download_materialBadgeTextView: com.matrixxun.starry.badgetextview.MaterialBadgeTextView get() = findViewById(R.id.browser_item_download_materialBadgeTextView)
val Activity.browser_item_download_materialBadgeTextView: com.matrixxun.starry.badgetextview.MaterialBadgeTextView get() = findViewById(R.id.browser_item_download_materialBadgeTextView)
val View.browser_item_download_numberProgressBar: com.daimajia.numberprogressbar.NumberProgressBar get() = findViewById(R.id.browser_item_download_numberProgressBar)
val Activity.browser_item_download_numberProgressBar: com.daimajia.numberprogressbar.NumberProgressBar get() = findViewById(R.id.browser_item_download_numberProgressBar)
val View.browser_item_download_progressBar: ProgressBar get() = findViewById(R.id.browser_item_download_progressBar)
val Activity.browser_item_download_progressBar: ProgressBar get() = findViewById(R.id.browser_item_download_progressBar)
val View.browser_item_download_textView1: TextView get() = findViewById(R.id.browser_item_download_textView1)
val Activity.browser_item_download_textView1: TextView get() = findViewById(R.id.browser_item_download_textView1)
val View.browser_item_download_textView2: TextView get() = findViewById(R.id.browser_item_download_textView2)
val Activity.browser_item_download_textView2: TextView get() = findViewById(R.id.browser_item_download_textView2)
val View.browser_item_download_textView3: TextView get() = findViewById(R.id.browser_item_download_textView3)
val Activity.browser_item_download_textView3: TextView get() = findViewById(R.id.browser_item_download_textView3)
val View.browser_item_download_textView4: TextView get() = findViewById(R.id.browser_item_download_textView4)
val Activity.browser_item_download_textView4: TextView get() = findViewById(R.id.browser_item_download_textView4)
val View.browser_item_download_textView5: TextView get() = findViewById(R.id.browser_item_download_textView5)
val Activity.browser_item_download_textView5: TextView get() = findViewById(R.id.browser_item_download_textView5)
val View.browser_item_latest_imageView: ImageView get() = findViewById(R.id.browser_item_latest_imageView)
val Activity.browser_item_latest_imageView: ImageView get() = findViewById(R.id.browser_item_latest_imageView)
val View.browser_item_path_appCompatImageView: androidx.appcompat.widget.AppCompatImageView get() = findViewById(R.id.browser_item_path_appCompatImageView)
val Activity.browser_item_path_appCompatImageView: androidx.appcompat.widget.AppCompatImageView get() = findViewById(R.id.browser_item_path_appCompatImageView)
val View.browser_item_path_textView: TextView get() = findViewById(R.id.browser_item_path_textView)
val Activity.browser_item_path_textView: TextView get() = findViewById(R.id.browser_item_path_textView)
val View.browser_item_recent_imageView: ImageView get() = findViewById(R.id.browser_item_recent_imageView)
val Activity.browser_item_recent_imageView: ImageView get() = findViewById(R.id.browser_item_recent_imageView)
val View.browser_item_recent_progressBar: ProgressBar get() = findViewById(R.id.browser_item_recent_progressBar)
val Activity.browser_item_recent_progressBar: ProgressBar get() = findViewById(R.id.browser_item_recent_progressBar)
val View.browser_item_recent_textView: TextView get() = findViewById(R.id.browser_item_recent_textView)
val Activity.browser_item_recent_textView: TextView get() = findViewById(R.id.browser_item_recent_textView)
val View.browser_layout_content_browserContentRecyclerView: com.sethchhim.kuboo_client.ui.main.browser.custom.BrowserContentRecyclerView get() = findViewById(R.id.browser_layout_content_browserContentRecyclerView)
val Activity.browser_layout_content_browserContentRecyclerView: com.sethchhim.kuboo_client.ui.main.browser.custom.BrowserContentRecyclerView get() = findViewById(R.id.browser_layout_content_browserContentRecyclerView)
val View.browser_layout_pagination_button1: Button get() = findViewById(R.id.browser_layout_pagination_button1)
val Activity.browser_layout_pagination_button1: Button get() = findViewById(R.id.browser_layout_pagination_button1)
val View.browser_layout_pagination_button2: Button get() = findViewById(R.id.browser_layout_pagination_button2)
val Activity.browser_layout_pagination_button2: Button get() = findViewById(R.id.browser_layout_pagination_button2)
val View.browser_layout_pagination_linearLayout2: LinearLayout get() = findViewById(R.id.browser_layout_pagination_linearLayout2)
val Activity.browser_layout_pagination_linearLayout2: LinearLayout get() = findViewById(R.id.browser_layout_pagination_linearLayout2)
val View.browser_layout_pagination_textView1: TextView get() = findViewById(R.id.browser_layout_pagination_textView1)
val Activity.browser_layout_pagination_textView1: TextView get() = findViewById(R.id.browser_layout_pagination_textView1)
val View.browser_layout_pagination_textView3: TextView get() = findViewById(R.id.browser_layout_pagination_textView3)
val Activity.browser_layout_pagination_textView3: TextView get() = findViewById(R.id.browser_layout_pagination_textView3)
val View.home_layout_welcome_textView1: TextView get() = findViewById(R.id.home_layout_welcome_textView1)
val Activity.home_layout_welcome_textView1: TextView get() = findViewById(R.id.home_layout_welcome_textView1)
val View.home_layout_welcome_textView2: TextView get() = findViewById(R.id.home_layout_welcome_textView2)
val Activity.home_layout_welcome_textView2: TextView get() = findViewById(R.id.home_layout_welcome_textView2)
val View.home_layout_welcome_textView3: TextView get() = findViewById(R.id.home_layout_welcome_textView3)
val Activity.home_layout_welcome_textView3: TextView get() = findViewById(R.id.home_layout_welcome_textView3)
val View.home_layout_welcome_textView4: TextView get() = findViewById(R.id.home_layout_welcome_textView4)
val Activity.home_layout_welcome_textView4: TextView get() = findViewById(R.id.home_layout_welcome_textView4)
val View.login_item_imageView: ImageView get() = findViewById(R.id.login_item_imageView)
val Activity.login_item_imageView: ImageView get() = findViewById(R.id.login_item_imageView)
val View.login_item_sparkButton: com.varunest.sparkbutton.SparkButton get() = findViewById(R.id.login_item_sparkButton)
val Activity.login_item_sparkButton: com.varunest.sparkbutton.SparkButton get() = findViewById(R.id.login_item_sparkButton)
val View.main_layout_base_bottomNavigationView: com.google.android.material.bottomnavigation.BottomNavigationView get() = findViewById(R.id.main_layout_base_bottomNavigationView)
val Activity.main_layout_base_bottomNavigationView: com.google.android.material.bottomnavigation.BottomNavigationView get() = findViewById(R.id.main_layout_base_bottomNavigationView)
val View.main_layout_base_toolBar: androidx.appcompat.widget.Toolbar get() = findViewById(R.id.main_layout_base_toolBar)
val Activity.main_layout_base_toolBar: androidx.appcompat.widget.Toolbar get() = findViewById(R.id.main_layout_base_toolBar)
